cifar10_test:
  interval: 1
  metrics:
    - name: accuracy
    - name: bma_accuracy
    - name: bma_nll
    - name: nll
    - name: brier_score
    - name: calibration_error
      params:
        num_classes: 10
        num_bins: 15
        norm: l1
    - name: bma_calibration_error
      params:
        num_classes: 10
        num_bins: 15
        norm: l1
    - name: bma_predictive_entropy
    - name: bma_expected_entropy
    - name: bma_mutual_information
    - name: bma_predictive_variance
