fashion_mnist_test:
  interval: 1
  metrics:
    - name: accuracy
    - name: vacuity
    - name: dirichlet_strength
    - name: dirichlet_nll
    - name: dirichlet_digamma_nll
    - name: dirichlet_brier_score
    - name: dirichlet_expected_brier
    - name: dirichlet_calibration_error
      params:
        num_classes: 10
        num_bins: 15
        norm: l1
    - name: analytical_dirichlet_total_uncertainty
    - name: analytical_dirichlet_aleatoric_uncertainty
    - name: analytical_dirichlet_distributional_uncertainty
mnist_ood:
  interval: 1
  metrics:
    - name: vacuity
    - name: dirichlet_strength
    - name: bma_dirichlet_mutual_information
    - name: bma_dirichlet_predictive_entropy
random_noise_ood:
  interval: 1
  metrics:
    - name: vacuity
    - name: dirichlet_strength
    - name: bma_dirichlet_mutual_information
    - name: bma_dirichlet_predictive_entropy
