defaults:
  - datasets: cifar10
  - model: resnet20
  - training: bnn_sgld
  - _self_

seed: 1

model:
  params:
    output_layer_config:
      type: linear
      params:
        num_classes: 10

training:
  dataset: cifar10_train
  checkpoint:
    dataset: cifar10_test
  device: auto
  num_epochs: 500
  pretrained:
    enabled: true
    path: /home/ra65puy/ra65puy_lrz_mount/BNN-EDL/outputs/2026-03-09/18-45-55/best_model.pt
  wandb:
    project: bnn-edl
    name: cifar10_resnet20_bnn_sgld_pretrained_temperature_0.1
    summary_metrics:
      cifar10_test:
        - name: accuracy
          objective: maximize
        - name: loss
          objective: minimize
  likelihood:
    name: categorical
  prior:
    name: diagonal_normal
    sd: 1.0
    normalize: false
  optimizer:
    name: sgld
    lr: 0.01
    temperature: 0.1
  scheduler:
    enabled: false
  sampling:
    enabled: true
    start_epoch: 200
    sample_interval: 4
  early_stopping:
    enabled: false
    dataset: cifar10_test
    metric: accuracy
    patience: 20
    min_delta: 0.0
    objective: maximize
  evaluation:
    cifar10_test:
      interval: 1
      metrics:
        - name: accuracy
        - name: loss
        - name: bma_accuracy
        - name: bma_nll
        - name: nll
        - name: brier_score
        - name: calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: bma_calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: predictive_entropy
        - name: expected_entropy
        - name: mutual_information
        - name: predictive_variance
