defaults:
  - datasets: cifar10
  - model: resnet20
  - training: bnn_sgld
  - evaluation: bnn_cifar10_test
  - _self_

seed: 1

training:
  dataset: cifar10_train
  checkpoint:
    dataset: cifar10_test
  num_epochs: 500
  wandb:
    summary_metrics:
      cifar10_test:
        - name: accuracy
          objective: maximize
        - name: loss
          objective: minimize
  sampling:
    start_epoch: 100
    sample_interval: 20