defaults:
  - datasets: cifar10
  - model: resnet20_dirichlet
  - training: dirichlet_bnn_sgld
  - evaluation: dirichlet_bnn_cifar10
  - _self_

seed: 1

training:
  dataset: cifar10_train
  checkpoint:
    dataset: cifar10_test
  num_epochs: 500
  wandb:
    summary_metrics:
      cifar10_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
  sampling:
    start_epoch: 100
    sample_interval: 20
  sampler:
    params:
      lr: 0.001
