defaults:
  - datasets: cifar10
  - model: resnet20_dirichlet
  - training: edl
  - evaluation: edl_cifar10_test
  - _self_

seed: 1

training:
  dataset: cifar10_train
  checkpoint:
    dataset: cifar10_test
  loss:
    params:
      num_classes: 10
      annealing_step: 300
  wandb:
    summary_metrics:
      cifar10_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
  num_epochs: 400
  scheduler:
    params:
      T_max: 400
      eta_min: 0
