defaults:
  - datasets: cifar10
  - model: resnet20
  - training: edl
  - _self_

seed: 1

model:
  params:
    output_layer_config:
      type: dirichlet
      params:
        num_classes: 10

training:
  dataset: cifar10_train
  checkpoint:
    dataset: cifar10_test
  loss:
    name: edl_mse
    params:
      num_classes: 10
      annealing_step: 300
  early_stopping:
    enabled: false
    dataset: cifar10_test
    metric: accuracy
    patience: 10
    min_delta: 0.0
    objective: maximize
  wandb:
    project: bnn-edl
    name: edl_cifar10_resnet20_mse_loss
    summary_metrics:
      cifar10_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
  num_epochs: 300
  optimizer:
    name: sgd
    params:
      lr: 1e-1
      momentum: 0.9
      weight_decay: 1e-4
  scheduler:
    enabled: true
    name: cosine_annealing
    params:
      T_max: 300
      eta_min: 0
  evaluation:
    cifar10_test:
      interval: 1
      metrics:
        - name: accuracy
        - name: loss
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_nll
        - name: dirichlet_brier_score
        - name: dirichlet_predictive_entropy
        - name: dirichlet_expected_entropy
        - name: dirichlet_mutual_information
        - name: dirichlet_calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
