defaults:
  - datasets: fashion_mnist
  - model: resnet20_grayscale_dirichlet
  - training: dirichlet_bnn_sgld
  - evaluation: dirichlet_bnn_fashion_mnist
  - _self_

seed: 1

training:
  dataset: fashion_mnist_train
  checkpoint:
    dataset: fashion_mnist_test
  wandb:
    summary_metrics:
      fashion_mnist_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize   