defaults:
  - datasets: fashion_mnist
  - model: resnet20_grayscale_dirichlet
  - training: edl
  - evaluation: edl_fashion_mnist_val
  - _self_

seed: 1

training:
  dataset: fashion_mnist_train_split
  checkpoint:
    dataset: fashion_mnist_val
  wandb:
    summary_metrics:
      fashion_mnist_val:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
