defaults:
  - datasets: fashion_mnist
  - model: resnet20
  - training: dirichlet_gibbs_sgld
  - evaluation: dirichlet_bnn_fashion_mnist
  - _self_

seed: 1

model:
  params:
    in_channels: 1
    output_layer_config:
      type: dirichlet
      params:
        num_classes: 10

training:
  dataset: fashion_mnist_train
  checkpoint:
    dataset: fashion_mnist_test
  device: auto
  pretrained:
    enabled: false
    path: /Users/jpweideman/BNN-EDL/outputs/2026-03-28/19-10-58/best_model.pt
  wandb:
    name: fashion_mnist_dirichlet_joint_bnn_sgld_pretrained_edl
    summary_metrics:
      fashion_mnist_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
  sampler:
    params:
      lr: 1e-2
