defaults:
  - datasets: fashion_mnist
  - model: resnet20
  - training: standard
  - _self_

seed: 1

model:
  params:
    in_channels: 1

training:
  dataset: fashion_mnist_train
  checkpoint:
    dataset: fashion_mnist_test
  wandb:
    name: fashion_mnist_resnet20_sgd
    summary_metrics:
      fashion_mnist_test:
        - name: accuracy
          objective: maximize
        - name: loss
          objective: minimize
  optimizer:
    name: sgd
    lr: 1e-2
    momentum: 0.9
    weight_decay: 1e-4
  evaluation:
    fashion_mnist_test:
      interval: 1
      metrics:
        - name: accuracy
        - name: loss
        - name: nll
        - name: brier_score
        - name: calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1

