defaults:
  - datasets: fashion_mnist
  - model: resnet20
  - training: edl
  - _self_

seed: 1

model:
  params:
    in_channels: 1
    output_layer_config:
      type: dirichlet
      params:
        num_classes: 10

training:
  dataset: fashion_mnist_train
  checkpoint:
    dataset: fashion_mnist_test
  wandb:
    name: fashion_mnist_edl
    summary_metrics:
      fashion_mnist_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
  optimizer:
    name: sgd
    params:
      lr: 1e-2
  evaluation:
    fashion_mnist_test:
      interval: 1
      metrics:
        - name: accuracy
        - name: loss
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_nll
        - name: dirichlet_brier_score
        - name: dirichlet_calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: dirichlet_predictive_entropy
        - name: dirichlet_expected_entropy
        - name: dirichlet_mutual_information
    mnist_ood:
      interval: 1
      metrics:
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_mutual_information
        - name: dirichlet_predictive_entropy
    random_noise_ood:
      interval: 1
      metrics:
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_mutual_information
        - name: dirichlet_predictive_entropy
