defaults:
  - datasets: fashion_mnist
  - model: resnet20
  - training: bnn_sgld
  - _self_

seed: 1

model:
  params:
    in_channels: 1

training:
  dataset: fashion_mnist_train
  checkpoint:
    dataset: fashion_mnist_test
  pretrained:
    enabled: true
    path: /Users/jpweideman/BNN-EDL/outputs/2026-03-29/13-35-16/best_model.pt
  wandb:
    name: fashion_mnist_categorical_bnn_sgld_temperature_0.01
    summary_metrics:
      fashion_mnist_test:
        - name: accuracy
          objective: maximize
        - name: loss
          objective: minimize
  optimizer:
    name: sgld
    params:
      lr: 1e-1
      temperature: 0.01
  evaluation:
    fashion_mnist_test:
      interval: 1
      metrics:
        - name: accuracy
        - name: loss
        - name: bma_accuracy
        - name: bma_nll
        - name: nll
        - name: brier_score
        - name: calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: bma_calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: predictive_entropy
        - name: expected_entropy
        - name: mutual_information
        - name: predictive_variance
    mnist_ood:
      interval: 1
      metrics:
        - name: predictive_entropy
        - name: mutual_information
        - name: bma_nll
    random_noise_ood:
      interval: 1
      metrics:
        - name: predictive_entropy
        - name: mutual_information
        - name: bma_nll
