defaults:
  - datasets: fashion_mnist
  - model: resnet20
  - training: dirichlet_gibbs_sgld
  - _self_

seed: 1

model:
  params:
    in_channels: 1
    output_layer_config:
      type: dirichlet
      params:
        num_classes: 10

training:
  dataset: fashion_mnist_train
  checkpoint:
    dataset: fashion_mnist_test
  device: auto
  pretrained:
    enabled: true
    path: /Users/jpweideman/BNN-EDL/outputs/2026-03-28/19-10-58/best_model.pt
  wandb:
    name: fashion_mnist_dirichlet_joint_bnn_sgld_pretrained_edl
    summary_metrics:
      fashion_mnist_test:
        - name: accuracy
          objective: maximize
        - name: dirichlet_nll
          objective: minimize
  optimizer:
    params:
      lr: 1e-2
  evaluation:
    fashion_mnist_test:
      interval: 1
      metrics:
        - name: accuracy
        - name: loss
        - name: bma_dirichlet_accuracy
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_nll
        - name: bma_dirichlet_nll
        - name: dirichlet_brier_score
        - name: dirichlet_calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: bma_dirichlet_brier_score
        - name: bma_dirichlet_calibration_error
          params:
            num_classes: 10
            num_bins: 15
            norm: l1
        - name: dirichlet_predictive_entropy
        - name: dirichlet_expected_entropy
        - name: dirichlet_mutual_information
        - name: dirichlet_predictive_variance
    mnist_ood:
      interval: 1
      metrics:
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_mutual_information
        - name: dirichlet_predictive_entropy
    random_noise_ood:
      interval: 1
      metrics:
        - name: vacuity
        - name: dirichlet_strength
        - name: dirichlet_mutual_information
        - name: dirichlet_predictive_entropy
